// Code generated by goctl. DO NOT EDIT.
package types

type UserLogin struct {
	TwitterUrl string `json:"twitterUrl"`
	InviteId   string `json:"inviteId"`
}

type UserLoginReply struct {
	Token string `json:"token"`
}
